"""create tasks and task_attempts tables

Revision ID: 7037f873f0a1
Revises:
Create Date: 2026-09-13 15:33:28.126674

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7037f873f0a1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted by hand: the FK on
    # tasks.authoritative_attempt_id is circular with task_attempts.task_id,
    # so it can't be created inline on either CREATE TABLE. use_alter=True
    # tells SQLAlchemy's DDL compiler to omit it here; it must be added
    # afterwards via a separate ALTER TABLE (op.create_foreign_key below),
    # or it silently never gets created at all. ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_key", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "SUCCEEDED", "FAILED", "ABANDONED", name="task_status"),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("authoritative_attempt_id", sa.Integer(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_task_key"), "tasks", ["task_key"], unique=True)
    op.create_table(
        "task_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "outcome", sa.Enum("SUCCEEDED", "FAILED", name="attempt_outcome"), nullable=False
        ),
        sa.Column("failure_category", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_attempts_task_id"), "task_attempts", ["task_id"], unique=False)
    op.create_foreign_key(
        "fk_tasks_authoritative_attempt_id",
        "tasks",
        "task_attempts",
        ["authoritative_attempt_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_tasks_authoritative_attempt_id", "tasks", type_="foreignkey")
    op.drop_index(op.f("ix_task_attempts_task_id"), table_name="task_attempts")
    op.drop_table("task_attempts")
    op.drop_index(op.f("ix_tasks_task_key"), table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
    # Autogenerate doesn't emit these: dropping the tables leaves the Postgres
    # ENUM types behind, so a later upgrade fails on "type already exists".
    sa.Enum(name="task_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="attempt_outcome").drop(op.get_bind(), checkfirst=True)
